info:
  name: teambuiltinggateway
  description: TeamBuilting Gateway Service

server:
  port: ${PORT:9090}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false

zuul:
  ignore-local-service: false
  ignored-services: '*'
  sensitive-headers:
  prefix: /api
  routes:
    core:
      path: /core/**
      strip-prefix: false
      url: ${CORE_SERVICE}
    statistics:
      path: /statistics/**
      strip-prefix: false
      url: ${STATISTICS_SERVICE}
    experience:
      path: /experience/**
      strip-prefix: false
      url: ${EXPERIENCE_SERVICE}

auth0:
  domain: manuelarte.eu.auth0.com
  issuer: https://manuelarte.eu.auth0.com/
  clientId: XOBz4RdzWoMnpxAvXKtK9R8W9IODYKsl
  clientSecret: tvKvKZd1tigVIAGztcOELwKIj0B0DswEbLdRG1PWu7NfZXk6VGbGkWdQjFpTZmWp
  securedRoute: NOT_USED
  base64EncodedSecret: true
  authorityStrategy: ROLES
  defaultAuth0ApiSecurityEnabled: false
  signingAlgorithm: HS256
  #signingAlgorithm: RS256
  #publicKeyPath: certificate/cert.pem

---

spring:
  profiles: development
zuul:
  routes:
    core:
      url: http://localhost:8080/
    statistics:
      url: http://localhost:8081/
    experience:
      url: http://localhost:8082/

