info:
  name: teambuiltinggateway
  description: TeamBuilting Gateway Service

server:
  port: ${PORT:9090}

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    sensitive: false

zuul:
  prefix: /api/v1
  routes:
    teams:
      path: /teams/**
      strip-prefix: false
      url: ${TEAMS_SERVICE}
    players:
      path: /players/**
      strip-prefix: false
      url: ${PLAYERS_SERVICE}
    sports:
      path: /sports/**
      strip-prefix: false
      url: ${SPORTS_SERVICE}
    statistics:
      path: /statistics/**
      strip-prefix: false
      url: ${STATISTICS_SERVICE}
    experience:
      path: /experience/**
      strip-prefix: false
      url: ${EXPERIENCE_SERVICE}

---

auth0:
  domain: manuelarte.eu.auth0.com
  issuer: https://manuelarte.eu.auth0.com/
  clientId: XOBz4RdzWoMnpxAvXKtK9R8W9IODYKsl
  clientSecret: tvKvKZd1tigVIAGztcOELwKIj0B0DswEbLdRG1PWu7NfZXk6VGbGkWdQjFpTZmWp
  securedRoute: NOT_USED
  base64EncodedSecret: true
  authorityStrategy: ROLES
  defaultAuth0ApiSecurityEnabled: false
  signingAlgorithm: HS256
  #signingAlgorithm: RS256
  #publicKeyPath: certificate/cert.pem

